title: "Baby vs Tools"        # Titel van je site (optioneel)
description: "Vergelijking van babyproducten en tools"  # Optioneel
url: "https://www.hoegrootiseenbaby.nl"  # Jouw domein
baseurl: ""                   # Leeg, omdat je site op de root draait
theme: minima                 # Of jouw gekozen Jekyll-theme
markdown: kramdown            # Standaard voor Jekyll
